### ISSUE TITLE
 Character Class

### ISSUE THREAD

**Issue by DrewGlinsman** [DrewGlinsman/OneMoreSol#1]
We need a class for the character, with health, position, current gun equipped as fields and a move and shoot method.

**Comment by jackbowden** [comment]
@SoloCW is going to rename Player to MajorTom and begin implementation.
I'm going create KoratEmpire, to be inherited by our first enemy and sub-class, Grunt.

**Comment by DrewGlinsman** [comment]
MajorTom is finished with movement working
